server:
    port: 8099

spring:
    application:
        name: go-privates
    datasource:
        name: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/go-privates?useUnicode=true&characterEncoding=utf-8&useSSL=false

rocketmq:
    producer:
        group: ${spring.application.name}
        # namespace: ${spring.application.name}
    name-server: 127.0.0.1:9876

logging:
    file:
        path: /data/logs/go-privates