server:
    port: 0

spring:
    application:
        name: go-privates
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/go_privates?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: root
        password: 123456
elasticjob:
    reg-center:
        server-lists: 127.0.0.1:2181
        namespace: go-privates
    jobs:
        mySimpleJob:
            elasticJobClass: ai.lifo.goelasticjob.job.MySimpleJob
            cron: 0 * * * * ?
            sharding-total-count: 2
            sharding-item-parameters: 0=Beijing,1=Shanghai,2=Guangzhou
            description: 一分一次Job
            overwrite: true
            disabled: false
            failover: true
            misfire: false
            monitor-execution: true
            job-listener-types:
                - ai.lifo.goelasticjob.trace.GoElasticJobListener
        ThrownTestJob:
            elasticJobClass: ai.lifo.goelasticjob.job.ThrownTestJob
            cron: '0 0/2 0/1 * * ?'
            sharding-total-count: 1
            description: 测试异常Job
            overwrite: true
            disabled: true
            job-error-handler-type: ai.lifo.goelasticjob.trace.GoElasticJobErrorHandler
            job-listener-types:
                - ai.lifo.goelasticjob.trace.GoElasticJobListener
        myDataflowJob:
            elastic-job-class: ai.lifo.goelasticjob.job.MyDataflowJob
            cron: '1 0/2 * * * ?'
            sharding-total-count: 3
            overwrite: true
            disabled: true
            sharding-item-parameters: 0=Beijing,1=Shanghai,2=Guangzhou
            props:
                streaming.process: true

        myOneOffJob:
            job-bootstrap-bean-name: myOneOffJob
            elastic-job-class: ai.lifo.goelasticjob.job.MyTestOneJob
            sharding-total-count: 3
            sharding-item-parameters: 0=Beijing,1=Shanghai,2=Guangzhou
            # 错误处理策略:记录日志策略、记录作业异常日志，但不中断作业执行
            # LOG : 记录日志策略、记录作业异常日志，但不中断作业执行
            # THROW : 抛出异常策略	抛出系统异常并中断作业执行
            # IGNORE : 忽略异常策略	忽略系统异常且不中断作业执行
            # WECHAT : 企业微信通知策略	发送企业微信消息通知，但不中断作业执行
            job-error-handler-type: LOG
            overwrite: true
            disabled: true
#        scriptJob:
#            elastic-job-type: SCRIPT
#            cron: '0/5 * * * * ?' # 每5秒执行一次
#            sharding-total-count: 1
#            description: "Script Job"
#            overwrite: true
#            props:
#                script.command.line: "cmd /c echo SCRIPT Job: "
        manualScriptJob:
            elastic-job-type: SCRIPT
            job-bootstrap-bean-name: manualScriptJob
            sharding-total-count: 1
            description: "Manual Script Job"
            overwrite: true
            disabled: true
            props:
                script.command.line: "cmd /c echo MANUAL SCRIPT Job: " # 注意系统环境
    tracing:
        type: RDB
    dump:
#        port: 9888
        enabled: true
