server:
    port: 8711

spring:
    application:
        name: xd-late-service
    lifecycle:
        timeout-per-shutdown-phase: 60s # N时间只有如果没有处理完 也直接关闭
    thymeleaf:
        cache: false
    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.160.11.137:3306/test_jsd_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: hcadmin
        password: hcadmin123
mybatis:
    mapper-locations: classpath:mapper/*.xml