spring:
    redis:
        timeout: 50000
        database: 0
        lettuce:
            pool:
                max-active: 8
                max-wait: -1
                max-idle: 8
                min-idle: 0
        cluster:
            nodes: 127.0.0.1:7000, 127.0.0.1:7001, 127.0.0.1:7002, 127.0.0.1:7003, 127.0.0.1:7004, 127.0.0.1:7005
        password: 123456
management:
    health:
        db:
            enabled: false
mybatis-plus:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath*:/mapper/**/*.xml